services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: sandbox-rag-container
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=sandbox-rag
    ports:
      - "5432:5432"
    volumes:
      - .tmp\db:/var/lib/postgresql/data